version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.server:app --reload --host 0.0.0.0 --port 8000  # Enable hot reload 